name: Mulesoft CI
on: 
  pull_request:
    branches:  
      - main
env: 
   MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/mulesoft-github-actions-domain"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
          server-id: snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ secrets.ARTIFACTORY_USER}} # env variable for username in deploy
          server-password: ${{ secrets.ARTIFACTORY_PASSWORD}} # env variable for token in deploy
      - name: Build Mule app
        run: |
         mvn --batch-mode verify
         mkdir staging && cp target/*.jar staging
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }} # GITHUB_TOKEN is the default env for the password
